spring:
    hadoop:
        fsUri: hdfs://10.0.2.15:8020
        resourceManagerHost: 10.0.2.15
        resourceManagerPort: 8050
    yarn:
        appName: yarn-application
        applicationDir: /app/yarn-application/
        client:
            files:
                - "file:/hw/hw-5/yarn-container-0.1.0.jar"
                - "file:/hw/hw-5/yarn-appmaster-0.1.0.jar"
            launchcontext:
                archiveFile: yarn-appmaster-0.1.0.jar
        appmaster:
            appmasterClass: com.hd.master.CustomApplicationMaster
            containerCount: 1
            launchcontext:
                archiveFile: yarn-container-0.1.0.jar
