spring:
    hadoop:
        fsUri: hdfs://sandbox.hortonworks.com:8020
        resourceManagerHost: sandbox.hortonworks.com
         yarn:
                appName: yarn-am-ui
                applicationDir: /app/gs-yarn-basic/
                client:
                    class:
                appmaster:
                    containerCount: 1
                    launchcontext:
                        archiveFile: gs-yarn-basic-container-0.1.0.jar